builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/gscan/main.go
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: gz
    files:
      - none*
